[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
sslCertFile = "/path/ssl_certs/skyflow.pem"
sslKeyFile = "/path/ssl_certs/skyflow.key"

[browser]
serverAddress = "skyflow-kvgrowth.com"
serverPort = 8501