[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
sslCertFile = "/code/ssl_certs/fullchain.pem"
sslKeyFile = "/code/ssl_certs/privkey.key"

[browser]
serverAddress = "skyflow-kvgrowth.com"
serverPort = 8501
